### ISSUE TITLE
Cannot extract following email pattern From: "my@email.com" <my@email.com>

### ISSUE THREAD

**Issue by christianadriano** [christianadriano/SEWORLD-Statistics#1]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.charAt(String.java:658)
    at parser.ExtractPostData.extractEmail(ExtractPostData.java:267)
    at parser.ExtractPostData.extractSenderFromPost(ExtractPostData.java:249)
    at parser.ExtractPostData.readFileToPosts(ExtractPostData.java:103)
    at parser.ExtractPostData.run(ExtractPostData.java:44)
    at parser.ExtractPostData.main(ExtractPostData.java:25)

**Comment by christianadriano** [comment]
Changed how I parse the email. if there are "<" and ">", only consider those as enclosing an email address.
