### ISSUE TITLE
Cannot extract date

### ISSUE THREAD

**Issue by christianadriano** [christianadriano/SEWORLD-Statistics#2]
Date: Content-Transfer-Encoding: quoted-printable
Post: C://seworld//statistics////reject_job_phd//SEWORLD  approval required (4C461164) - LISTSERV@LISTSERV.ACM.ORG - 2015-03-23 0117.eml
java.text.ParseException: Unparseable date: "Content-Transfer-Encoding: quoted-printable"
    at java.text.DateFormat.parse(DateFormat.java:357)
    at parser.PostDate.<init>(PostDate.java:39)
    at parser.Post.setReceivedDate(Post.java:50)
    at parser.ExtractPostData.readFileToPosts(ExtractPostData.java:101)
    at parser.ExtractPostData.run(ExtractPostData.java:44)
    at parser.ExtractPostData.main(ExtractPostData.java:25)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:400)
    at java.util.ArrayList.get(ArrayList.java:413)
    at parser.ExtractPostData.extractSubjectFromPost(ExtractPostData.java:159)
    at parser.ExtractPostData.readFileToPosts(ExtractPostData.java:102)
    at parser.ExtractPostData.run(ExtractPostData.java:44)
    at parser.ExtractPostData.main(ExtractPostData.java:25)

**Comment by christianadriano** [comment]
Fixed, I had to change the files. Move the "Date: " line upwards, because it was located after the last token (Content-type).
